### ISSUE TITLE
Arrumar .gitignore

### ISSUE THREAD

**Issue by nbfontana** [alexandredavi/processamento-digital-imagens#4]
O .gitignore não tá ignorando alguns arquivos, tá correto?

Arquivos:
-  .classpath
-  .project
-  .settings (pasta)

**Comment by alexandredavi** [comment]
Pelo motivo de não estar utilizando do maven para gerenciar as dependencias devido ao local onde implento o projeto ter bloqueios na rede, preciso commitar estes arquivos para que nao precise configurar novamente as dependencias quando utilizo o projetos em outras maquinas.

**Comment by nbfontana** [comment]
Bom argumento Ahahah
Em 01/04/2016 18:33, "Alexandre Davi Zanelatto" notifications@github.com
escreveu:
